apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-app
  template:
    metadata:


      labels:
        app: analytics-app
    spec:
      containers:
        - name: analytics-app
          image: sar0234/student-analytics:latest
          command: [ "sh", "-c", "java -jar /app.jar && sleep 3600" ]